a=int(input('Height : '))
Height_after_one_year=(a*2)
Height_after_second_year=(Height_after_one_year*2)
Height_after_third_year=(Height_after_second_year*2)
Height_after_fourth_year=(Height_after_third_year*2)
Height_after_fifth_year=(Height_after_fourth_year*2)
print('Height :',a)
print('Height after one year :',Height_after_one_year)
print('Height after second year :',Height_after_second_year)
print('Height after third year :',Height_after_third_year)
print('Height after fourth year :',Height_after_fourth_year)
print('Height after fifth year :',Height_after_fifth_year)